### ISSUE TITLE
Add inet_cidr to included_applications

### ISSUE THREAD

**Issue by philipgiuliani** [ajvondrak/remote_ip#1]
`inet_cidr` should be added to `included_applications`, otherwise it will not be added in the release and the application will crash on startup.

**Comment by ajvondrak** [comment]
Thanks! Hadn't crossed the bridge of working with Elixir releases yet, so I'll take your word on this & push out the fix. :)

**Comment by ajvondrak** [comment]
By the way, do you know of an easy way to tell what will or won't break a release? There are two other declared deps that don't have corresponding applications:`combine` and `plug`.

I suppose `plug` will probably be included as an application in whatever project you're using `remote_ip` with already. Do you know if `combine` will similarly break releases?

**Comment by philipgiuliani** [comment]
Oh I completely forgot to answer... Actually you have to add every dependency you are using in production. Elixir 1.4 will automate this and you don't have to define them anymore.

In `applications` you add all dependencies that are running as application, and in `included_application` you add libraries.

Plug is already included in phoenix. Actually you probably also have to add `combine` in `included_applications`.

You can read about it here http://blog.plataformatec.com.br/2016/07/understanding-deps-and-applications-in-your-mixfile/

**Comment by ajvondrak** [comment]
@philipgiuliani Thanks for the follow-up! I've only now just gotten around to addressing this, myself. :)

Application inference sounds super useful. I see Elixir 1.4 was just released recently, I'll definitely have to play around with it.

In the meantime, I verified that (indeed) the lack of `:combine` breaks when trying to use `RemoteIp.Headers.Forwarded` from a Distillery release. (First time using Distillery, actually, so it's a learning process for me.) I'll add `:combine` to the `:included_applications` - and what the heck, even add `:plug` to the `:applications`, just to cover all the bases. :+1: Thanks again.

**Comment by philipgiuliani** [comment]
Yes perfect, so you can also use it without using Phoenix. Great job! With Elixir 1.4 you can just remove all of this :)
