### ISSUE TITLE
RFC1918 IPs shouldn't be discarded by default

### ISSUE THREAD

**Issue by hrefhref** [ajvondrak/remote_ip#8]
Hi,
I started using this plug in applications that are only deployed in a VPN/LAN. However, it discards all the clients IPs as they are RFC1918 IPs (mostly 10/8, some 192.168/16).

It would be nice to allow an option to not discard some of theses reserved networks. Maybe even sub-ranges if that makes more sense (e.g. our VPN is 10.42/16).

**Comment by ajvondrak** [comment]
See, I was paranoid about this exact issue while hard-coding the private networks in https://github.com/ajvondrak/remote_ip/blob/827762a087cd10b897ef7a4ad1d8c2c7c5a7301f/lib/remote_ip.ex#L55-L64 I think I was just copying what Rails was doing: https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L31-L42

What do you think about maybe lifting `@reserved` out into another keyword option, where the default is the currently-hard-coded list? Then you could `init` the plug with `reserved: [...]`. I guess for your use case a whitelist might make more sense, though. 🤔
